### ISSUE TITLE
Information about the recordings

### ISSUE THREAD

**Issue by silvada95** [SSIGPRO/PEDRo-Event-Based-Dataset#1]
Hi,

You mentioned in the paper that the dataset was extracted from 119 recordings. Is it possible to provide information about which frames belong to which recordings?

**Comment by ChiaraBoretti** [comment]
Hi, 

Thanks for your interest in PEDRo! In the Zenodo repository where the dataset is available, you can find the "info.txt" file which contains information about how the frames have been divided into train, validation, and test set but it also specifies the source recordings from which each frame has been extracted.
