### ISSUE TITLE
numpy.zip corrupt?

### ISSUE THREAD

**Issue by agirbau** [SSIGPRO/PEDRo-Event-Based-Dataset#2]
Hello!

I'm trying to download the dataset and I get an error when trying to unzip "numpy.zip". I have checked the checksum and it's the same as in the webpage. Maybe it's corrupt somehow?

**Comment by 233AvavAvA** [comment]
me too

**Comment by ChiaraBoretti** [comment]
Hello!  
Thank you for your interest in the PEDRo Dataset. We've recently updated to version 2.0, which includes a new "numpy.zip" folder. Please ensure you download the latest version of the dataset (v2.0) for solving "numpy.zip" folder problems.

**Comment by philippebich** [comment]
I have tested the new version of the dataset and I confirm the problem is now solved. I close the issue. Thanks everyone!
