### ISSUE TITLE
The numpy.zip file downloads but is corrupted.

### ISSUE THREAD

**Issue by ibugueno** [SSIGPRO/PEDRo-Event-Based-Dataset#4]
Dear authors,

Thank you very much for this contribution, would it be possible to indicate how to download the numpy.zip file? When I download it manually or through external libraries, it is corrupted

Thank you in advance

**Comment by SageCao1125** [comment]
same problem.

**Comment by ChiaraBoretti** [comment]
Hello!  
Thank you for your interest in the PEDRo Dataset. We've recently updated to version 2.0, which includes a new numpy.zip folder. Please ensure you download the latest version of the dataset (v2.0) for solving "numpy.zip" folder problems.

**Comment by philippebich** [comment]
I have tested the new version of the dataset and I confirm the problem is now solved. I close the issue. Thanks everyone!
